baseURL = 'https://luyee6813.github.io'
languageCode = 'en-us'
title = '#!/bin/note'
theme = 'github-style'
pygmentsCodeFences = true
pygmentsUseClasses = true

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
author = "LuYee6813"
description = "å€‹äººå®‰å…¨ç ”ç©¶èˆ‡ CTF writeups"
github = "luyee6813"
email = "luyee6813@gmail.com"
url = "https://luyee6813.github.io"
keywords = "cybersecurity, penetration testing, CTF, writeups, infosec, security research"
rss = true
lastmod = true
favicon = "/favicon.ico"
avatar = "/images/avatar.png"
location = "Taiwan"
userStatusEmoji = "ğŸ”"
enableGitalk = false
enableSearch = true

[[params.links]]
title = "GitHub"
href = "https://github.com/luyee6813"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
style = "github"

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false
